[build]
  command = "go build -o bin/main ."
  publish = "."
  functions = "functions"

[build.environment]
  GO_VERSION = "1.21"
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  YARN_FLAGS = "--version"
  YARN_VERSION = "1.22.0"
  NPM_VERSION = ""

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-functions-install-core"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
